/* AUTO-GENERATED by build.py — edit questions.json + app.core.js, then re-run. */
var DATA = {
  "meta": {
    "title": "Amazon SDE Intern — Mock Online Assessment",
    "subtitle": "Built on reported 2025–2026 question patterns",
    "sections": [
      {
        "id": "debug",
        "name": "Code Debugging",
        "minutes": 20,
        "note": "7 questions. Find the bug."
      },
      {
        "id": "coding",
        "name": "Coding Assessment",
        "minutes": 70,
        "note": "2 problems. Write your approach and code."
      },
      {
        "id": "corecs",
        "name": "Core CS MCQs",
        "minutes": 25,
        "note": "20 questions across OS, Linux, DBMS, Algorithms, Java."
      },
      {
        "id": "reasoning",
        "name": "Logical Reasoning",
        "minutes": 20,
        "note": "10 questions. No going back."
      },
      {
        "id": "worksim",
        "name": "Work Simulation",
        "minutes": 20,
        "note": "8 scenarios scored against Leadership Principles."
      },
      {
        "id": "workstyle",
        "name": "Workstyles Assessment",
        "minutes": 10,
        "note": "12 paired statements. Consistency is the signal."
      }
    ]
  },
  "debug": [
    {
      "id": "d1",
      "prompt": "This should return the maximum subarray sum. It returns the wrong answer for all-negative arrays.",
      "code": "int maxSubArray(int[] a) {\n    int best = 0;          // line 2\n    int cur = 0;\n    for (int v : a) {\n        cur = Math.max(v, cur + v);\n        best = Math.max(best, cur);\n    }\n    return best;\n}",
      "options": [
        "Line 2: `best` should be initialised to `a[0]`, not `0`",
        "Line 5: should be `cur = cur + v`",
        "Line 6: should be `best = cur`",
        "The loop should start from index 1"
      ],
      "answer": 0,
      "explain": "Initialising best to 0 means an all-negative array returns 0, which is not a valid subarray sum. Initialise best = a[0] (and cur = a[0], looping from index 1) so at least one element is always taken."
    },
    {
      "id": "d2",
      "prompt": "Binary search that should return the index of target, or -1. It infinite-loops on some inputs.",
      "code": "int search(int[] a, int t) {\n    int lo = 0, hi = a.length - 1;\n    while (lo <= hi) {\n        int mid = (lo + hi) / 2;\n        if (a[mid] == t) return mid;\n        else if (a[mid] < t) lo = mid;      // line 6\n        else hi = mid;                       // line 7\n    }\n    return -1;\n}",
      "options": [
        "Line 4: overflow in `(lo + hi) / 2`",
        "Lines 6 and 7: should be `lo = mid + 1` and `hi = mid - 1`",
        "Line 3: should be `lo < hi`",
        "Line 9: should return `lo`"
      ],
      "answer": 1,
      "explain": "Without the +1 / -1 the window never shrinks when hi = lo + 1, so the loop spins forever. Overflow in (lo+hi)/2 is a real secondary issue — lo + (hi-lo)/2 is safer — but it does not cause the infinite loop."
    },
    {
      "id": "d3",
      "prompt": "Should count vowels in a string. Always returns 0.",
      "code": "int countVowels(String s) {\n    int c = 0;\n    String v = \"aeiou\";\n    for (int i = 0; i < s.length(); i++) {\n        if (v.indexOf(s.charAt(i)) == -1) c++;   // line 5\n    }\n    return c;\n}",
      "options": [
        "Line 4: should be `i <= s.length()`",
        "Line 5: the condition is inverted — should be `!= -1`",
        "Line 3: missing uppercase vowels",
        "Line 2: `c` should start at 1"
      ],
      "answer": 1,
      "explain": "indexOf returns -1 when the char is NOT found. The condition counts consonants. It returns 0 only for all-vowel strings, but the logical bug is the inverted comparison."
    },
    {
      "id": "d4",
      "prompt": "Should reverse a linked list. Returns only the last node.",
      "code": "Node reverse(Node head) {\n    Node prev = null, cur = head;\n    while (cur != null) {\n        Node next = cur.next;\n        cur.next = prev;\n        prev = cur;\n        cur = cur.next;        // line 7\n    }\n    return prev;\n}",
      "options": [
        "Line 9: should return `cur`",
        "Line 5: should be `cur.next = next`",
        "Line 7: should be `cur = next` — `cur.next` was just overwritten",
        "Line 2: `prev` should start at `head`"
      ],
      "answer": 2,
      "explain": "Line 5 already reassigned cur.next to prev, so line 7 walks backwards. Use the saved `next` reference."
    },
    {
      "id": "d5",
      "prompt": "Should return true if the array contains a duplicate. Returns false for [1,1].",
      "code": "boolean hasDup(int[] a) {\n    Set<Integer> seen = new HashSet<>();\n    for (int v : a) {\n        seen.add(v);\n        if (seen.contains(v)) continue;   // line 5\n        return true;\n    }\n    return false;\n}",
      "options": [
        "Line 4 and 5 are in the wrong order — check membership before adding",
        "Line 8: should return `true`",
        "Line 2: should use a `List`",
        "Line 5: `continue` should be `break`"
      ],
      "answer": 0,
      "explain": "Adding first guarantees contains() is always true, so it always continues. Check `if (!seen.add(v)) return true;` — add() returns false when the element was already present."
    },
    {
      "id": "d6",
      "prompt": "Should compute n! for n >= 0. StackOverflowError for n = 0.",
      "code": "long fact(int n) {\n    if (n == 1) return 1;      // line 2\n    return n * fact(n - 1);\n}",
      "options": [
        "Line 3: should be `fact(n)` ",
        "Line 2: base case should be `n <= 1`",
        "Line 1: return type should be `int`",
        "Line 3: overflow for large n"
      ],
      "answer": 1,
      "explain": "With n = 0 it recurses to -1, -2, ... forever. `n <= 1` (or n == 0) terminates correctly. Overflow past n = 20 is a real but separate concern."
    },
    {
      "id": "d7",
      "prompt": "Should remove all occurrences of a value from a list. Skips some elements.",
      "code": "void removeAll(List<Integer> list, int val) {\n    for (int i = 0; i < list.size(); i++) {\n        if (list.get(i) == val) {\n            list.remove(i);      // line 4\n        }\n    }\n}",
      "options": [
        "Line 4: `remove(i)` shifts elements left, so `i` must be decremented after removal",
        "Line 3: should use `.equals()`",
        "Line 2: should iterate backwards only",
        "Line 4: should be `list.remove(val)`"
      ],
      "answer": 0,
      "explain": "After removing index i, the next element slides into position i but the loop increments past it. Fix with i-- after removal, or iterate backwards, or use an Iterator. Note: remove(int) vs remove(Object) is also a classic Java trap with boxed Integers."
    }
  ],
  "coding": [
    {
      "id": "c1",
      "title": "Minimum Array Operations",
      "difficulty": "Medium",
      "suggested": 25,
      "statement": "Given an integer array arr, you may pick an index i and a value x where -10 <= x <= 10, and set arr[i] = x. Modify the array so that the sum of every subarray of length greater than 1 is non-negative. Return the minimum number of operations required.\n\nExample:\narr = [2, 5, -3, -1, 2]  ->  1\nSetting index 2 to 10 gives [2, 5, 10, -1, 2], where every subarray of length > 1 has a non-negative sum.\n\nConstraints: 1 <= arr.length <= 10^5, -10^9 <= arr[i] <= 10^9",
      "source": "Reported in 2026 Amazon OA",
      "hint": "Track a running cumulative sum. What must be true the moment it dips below zero?",
      "approach": "Prefix sum with state reset. Walk the array accumulating a running sum. Whenever the running sum goes negative, that prefix already violates the constraint — count one operation and reset the running sum to 0. Any violating window must pass through such a dip, and repairing at the earliest dip lifts every window through that point.",
      "complexity": "O(n) time, O(1) space",
      "solution": "public int minOperations(int[] arr) {\n    long running = 0;\n    int ops = 0;\n    for (int v : arr) {\n        running += v;\n        if (running < 0) {\n            ops++;\n            running = 0;\n        }\n    }\n    return ops;\n}"
    },
    {
      "id": "c2",
      "title": "Server Allocation Cost",
      "difficulty": "Medium-Hard",
      "suggested": 35,
      "statement": "You are given an array servers, where index i is a server ID and servers[i] is the number of idle instances on it. m customers arrive one at a time. Each customer picks the server with the most idle instances and rents exactly one instance from it. The cost charged to that customer is (max_instances + min_instances), where both values are measured across all servers BEFORE that customer's selection. After all m customers, return the total cumulative cost.\n\nExample:\nservers = [3, 1, 4], m = 3\nCustomer 1: max=4, min=1 -> cost 5. servers becomes [3,1,3]\nCustomer 2: max=3, min=1 -> cost 4. servers becomes [3,1,2]\nCustomer 3: max=3, min=1 -> cost 4.\nTotal = 13\n\nConstraints: 1 <= servers.length <= 10^5, 1 <= m <= 10^5",
      "source": "Reported in 2026 Amazon OA",
      "hint": "You need the maximum and the minimum of a changing multiset, quickly. What structure gives you both ends in log n?",
      "approach": "Use a TreeMap<Integer,Integer> as a multiset: firstKey() is the min, lastKey() is the max, both O(log n). Read cost before mutating, then decrement the chosen max and reinsert. A dual max-heap/min-heap works too but requires lazy deletion to stay in sync, which is a common source of bugs — mention that trade-off out loud.",
      "complexity": "O(m log n) time, O(n) space",
      "solution": "public long totalCost(int[] servers, int m) {\n    TreeMap<Integer, Integer> ms = new TreeMap<>();\n    for (int s : servers) ms.merge(s, 1, Integer::sum);\n\n    long total = 0;\n    for (int c = 0; c < m; c++) {\n        int hi = ms.lastKey();\n        int lo = ms.firstKey();\n        total += (long) hi + lo;\n\n        if (ms.merge(hi, -1, Integer::sum) == 0) ms.remove(hi);\n        ms.merge(hi - 1, 1, Integer::sum);\n    }\n    return total;\n}"
    }
  ],
  "corecs": [
    {
      "topic": "OS",
      "q": "A process executes `fork()` three times sequentially. How many processes exist in total, including the original?",
      "options": [
        "4",
        "6",
        "8",
        "16"
      ],
      "answer": 2,
      "explain": "Each fork doubles the process count: 2^3 = 8 total."
    },
    {
      "topic": "OS",
      "q": "Which is NOT one of the four Coffman conditions for deadlock?",
      "options": [
        "Mutual exclusion",
        "Hold and wait",
        "Preemption",
        "Circular wait"
      ],
      "answer": 2,
      "explain": "The fourth condition is NO preemption. Allowing preemption breaks deadlock."
    },
    {
      "topic": "OS",
      "q": "Reference string 1,2,3,4,1,2,5 with 3 frames using FIFO. How many page faults?",
      "options": [
        "5",
        "6",
        "7",
        "9"
      ],
      "answer": 2,
      "explain": "1,2,3 fault (3). 4 evicts 1 (4). 1 evicts 2 (5). 2 evicts 3 (6). 5 evicts 4 (7). Total 7."
    },
    {
      "topic": "OS",
      "q": "A semaphore initialised to 3 allows how many processes into the critical section concurrently?",
      "options": [
        "1",
        "3",
        "Unlimited",
        "0"
      ],
      "answer": 1,
      "explain": "A counting semaphore initialised to N permits N concurrent entries. Initialised to 1 it is a binary semaphore/mutex."
    },
    {
      "topic": "Linux",
      "q": "`chmod 640 file.txt` gives which permissions?",
      "options": [
        "rw-r----- ",
        "rwxr-x---",
        "r--rw----",
        "rw-rw-r--"
      ],
      "answer": 0,
      "explain": "6 = rw- (owner), 4 = r-- (group), 0 = --- (others)."
    },
    {
      "topic": "Linux",
      "q": "Which command prints the number of lines in file.log containing the word ERROR?",
      "options": [
        "grep -c ERROR file.log",
        "grep -n ERROR file.log",
        "wc -l file.log",
        "cat file.log | ERROR"
      ],
      "answer": 0,
      "explain": "-c counts matching lines. -n prefixes line numbers instead of counting."
    },
    {
      "topic": "Linux",
      "q": "What is the difference between a hard link and a symbolic link?",
      "options": [
        "A hard link points to the same inode; a symlink stores a path and breaks if the target moves",
        "A symlink points to the same inode; a hard link stores a path",
        "There is no difference",
        "Hard links only work across filesystems"
      ],
      "answer": 0,
      "explain": "Hard links share the inode and survive renames of the original. Symlinks store a path and dangle if the target is removed. Hard links cannot cross filesystems."
    },
    {
      "topic": "Linux",
      "q": "`2>&1` in a shell command does what?",
      "options": [
        "Redirects stderr into stdout",
        "Redirects stdout into stderr",
        "Runs the command twice",
        "Sends output to file descriptor 21"
      ],
      "answer": 0,
      "explain": "It duplicates fd 2 (stderr) onto fd 1 (stdout), so both flow to the same destination."
    },
    {
      "topic": "DBMS",
      "q": "A relation has FDs A -> B and B -> C, with A as the primary key. What is the highest normal form it satisfies?",
      "options": [
        "1NF",
        "2NF",
        "3NF",
        "BCNF"
      ],
      "answer": 1,
      "explain": "A -> B -> C is a transitive dependency on the key, which violates 3NF. It is in 2NF."
    },
    {
      "topic": "DBMS",
      "q": "Which isolation level prevents dirty reads and non-repeatable reads but still allows phantom reads?",
      "options": [
        "READ UNCOMMITTED",
        "READ COMMITTED",
        "REPEATABLE READ",
        "SERIALIZABLE"
      ],
      "answer": 2,
      "explain": "REPEATABLE READ locks rows already read but not ranges, so newly inserted rows matching the predicate can still appear."
    },
    {
      "topic": "DBMS",
      "q": "Table A has 5 rows, Table B has 3 rows. How many rows does `SELECT * FROM A CROSS JOIN B` return?",
      "options": [
        "8",
        "15",
        "5",
        "3"
      ],
      "answer": 1,
      "explain": "A cross join is the Cartesian product: 5 x 3 = 15."
    },
    {
      "topic": "DBMS",
      "q": "Which is true of WHERE vs HAVING?",
      "options": [
        "WHERE filters rows before grouping; HAVING filters groups after aggregation",
        "HAVING filters rows before grouping",
        "They are interchangeable",
        "WHERE cannot be used with GROUP BY"
      ],
      "answer": 0,
      "explain": "WHERE applies to individual rows pre-aggregation. HAVING applies to aggregate results post-GROUP BY."
    },
    {
      "topic": "Algorithms",
      "q": "Worst-case time complexity of quicksort, and when it occurs?",
      "options": [
        "O(n log n), always",
        "O(n^2), when the pivot is always the smallest or largest element",
        "O(n^2), when the array is random",
        "O(n), on sorted input"
      ],
      "answer": 1,
      "explain": "A maximally unbalanced partition at every level gives O(n^2). Sorted input with a first-element pivot triggers it."
    },
    {
      "topic": "Algorithms",
      "q": "Solve T(n) = 2T(n/2) + n using the Master theorem.",
      "options": [
        "O(n)",
        "O(n log n)",
        "O(n^2)",
        "O(log n)"
      ],
      "answer": 1,
      "explain": "a=2, b=2, so n^(log_b a) = n. f(n) = n matches, giving Case 2: O(n log n)."
    },
    {
      "topic": "Algorithms",
      "q": "Why does Dijkstra's algorithm fail on graphs with negative edge weights?",
      "options": [
        "It runs forever",
        "Once a node is finalised it is never revisited, but a negative edge could later offer a shorter path",
        "It cannot handle directed graphs",
        "It requires a connected graph"
      ],
      "answer": 1,
      "explain": "Dijkstra's greedy invariant assumes distances only grow as you extend a path. Negative edges break that, so use Bellman-Ford."
    },
    {
      "topic": "Algorithms",
      "q": "Which structure gives O(1) average lookup but O(n) worst case?",
      "options": [
        "Balanced BST",
        "Hash table",
        "Heap",
        "Sorted array"
      ],
      "answer": 1,
      "explain": "With every key colliding into one bucket, a hash table degenerates to a linked-list scan. Java 8+ converts long buckets to trees, softening this to O(log n)."
    },
    {
      "topic": "Java",
      "q": "What does `new Integer(127) == new Integer(127)` evaluate to?",
      "options": [
        "true",
        "false",
        "Compile error",
        "Depends on the JVM"
      ],
      "answer": 1,
      "explain": "`new` forces distinct objects, so reference comparison is false. Note that `Integer a = 127; Integer b = 127; a == b` IS true due to the Integer cache for -128..127."
    },
    {
      "topic": "Java",
      "q": "Which collection maintains insertion order AND allows O(1) average lookup by key?",
      "options": [
        "HashMap",
        "TreeMap",
        "LinkedHashMap",
        "Hashtable"
      ],
      "answer": 2,
      "explain": "LinkedHashMap keeps a doubly-linked list across entries for predictable iteration order while retaining hash lookup."
    },
    {
      "topic": "Java",
      "q": "A method has a `return` in `try` and a `return` in `finally`. Which wins?",
      "options": [
        "The try block's return",
        "The finally block's return",
        "Compile error",
        "Both execute"
      ],
      "answer": 1,
      "explain": "The finally block's return overrides and discards the try block's value. This is a well-known anti-pattern."
    },
    {
      "topic": "Java",
      "q": "Which is a checked exception?",
      "options": [
        "NullPointerException",
        "IOException",
        "ArrayIndexOutOfBoundsException",
        "ArithmeticException"
      ],
      "answer": 1,
      "explain": "IOException extends Exception and must be declared or caught. The others extend RuntimeException and are unchecked."
    }
  ],
  "reasoning": [
    {
      "q": "Complete the series: 3, 7, 16, 35, 74, ?",
      "options": [
        "151",
        "153",
        "148",
        "160"
      ],
      "answer": 1,
      "explain": "Rule: x2 then +1, +2, +3, +4, +5. 74x2 + 5 = 153."
    },
    {
      "q": "If one program solves a problem of size N in X steps, and the algorithm is O(N^2), roughly how many steps for size 2N?",
      "options": [
        "2X",
        "4X",
        "X/2",
        "X^2"
      ],
      "answer": 1,
      "explain": "Quadratic growth: doubling the input quadruples the work."
    },
    {
      "q": "All engineers are problem solvers. Some problem solvers are designers. Which necessarily follows?",
      "options": [
        "Some engineers are designers",
        "All designers are engineers",
        "No valid conclusion about engineers and designers",
        "All problem solvers are engineers"
      ],
      "answer": 2,
      "explain": "The overlap between problem solvers and designers may fall entirely outside the engineer subset, so nothing necessarily follows."
    },
    {
      "q": "A is B's father. C is B's sister. D is C's mother. How is D related to A?",
      "options": [
        "Sister",
        "Wife",
        "Daughter",
        "Mother"
      ],
      "answer": 1,
      "explain": "C and B share parents. D is their mother; A is their father. D is A's wife."
    },
    {
      "q": "A server processes 240 requests in 4 minutes. Three identical servers process how many in 90 seconds?",
      "options": [
        "180",
        "240",
        "270",
        "300"
      ],
      "answer": 2,
      "explain": "One server: 60 req/min. Three: 180 req/min. In 1.5 min: 270."
    },
    {
      "q": "Facing north, you turn 90 degrees right, then 180 degrees, then 90 degrees left. Which way are you facing?",
      "options": [
        "North",
        "South",
        "East",
        "West"
      ],
      "answer": 1,
      "explain": "North, turn right 90 = East. Turn 180 = West. Turn left 90 from West = South."
    },
    {
      "q": "In a code, AMAZON is written as BNBAPO. How is CLOUD written?",
      "options": [
        "DMPVE",
        "DMPWE",
        "DNPVE",
        "EMPVE"
      ],
      "answer": 0,
      "explain": "Each letter shifts +1. C->D, L->M, O->P, U->V, D->E = DMPVE."
    },
    {
      "q": "Deploys succeed 80% of the time. Two independent deploys. Probability both succeed?",
      "options": [
        "0.8",
        "0.64",
        "0.16",
        "0.96"
      ],
      "answer": 1,
      "explain": "0.8 x 0.8 = 0.64."
    },
    {
      "q": "Five servers S1..S5 are in a rack. S3 is directly above S1. S5 is at the bottom. S2 is directly above S3. Which is at the top?",
      "options": [
        "S1",
        "S2",
        "S3",
        "S4"
      ],
      "answer": 3,
      "explain": "Bottom to top: S5, S1, S3, S2, leaving S4 at the top."
    },
    {
      "q": "A cache hit costs 2ms, a miss costs 50ms. With a 90% hit rate, what is the average latency?",
      "options": [
        "6.8ms",
        "7.4ms",
        "26ms",
        "4.8ms"
      ],
      "answer": 0,
      "explain": "0.9(2) + 0.1(50) = 1.8 + 5 = 6.8ms."
    }
  ],
  "worksim": [
    {
      "scenario": "It is 4pm Friday. A monitoring alert shows 3% of checkout requests are failing with a 500 error. You have not touched that service. Your own feature is due Monday. What do you do first?",
      "options": [
        "Finish your feature — the checkout service belongs to another team",
        "Check the error logs and recent deploys yourself, then post the specific finding in the team channel and flag the customer impact",
        "Immediately page your manager and wait for direction",
        "Post 'checkout looks broken?' in the channel and go back to your feature"
      ],
      "best": 1,
      "explain": "Ownership plus Dive Deep. You gather evidence first so your escalation is actionable, and you surface customer impact rather than saying 'not my job'. Option 2 is passive; option 0 is the classic ownership failure; option 3 escalates with no information."
    },
    {
      "scenario": "Your tech lead chose a caching approach you believe will not scale. You have benchmark data suggesting a problem at 10x load. The decision meeting is tomorrow.",
      "options": [
        "Stay quiet — you are an intern and the lead has more context",
        "Raise it in the meeting with your benchmark data, ask what you might be missing, and if the decision stands, commit fully and help implement it",
        "Email skip-level leadership about the concern",
        "Implement it your own way and show it works later"
      ],
      "best": 1,
      "explain": "Have Backbone; Disagree and Commit, done correctly: evidence-based, respectful, in the right forum, and with genuine commitment afterwards. Option 0 lacks backbone; option 2 skips the chain; option 3 is disagree-and-defy."
    },
    {
      "scenario": "You shipped a change that silently broke a report used by an ops team. You notice it two days later. Nobody else has flagged it.",
      "options": [
        "Quietly fix it and say nothing since nobody noticed",
        "Fix it, then tell your manager and the ops team what broke, for how long, what data was affected, and what guardrail you are adding",
        "Wait to see if the ops team complains first",
        "Fix it and mention it casually in standup weeks later"
      ],
      "best": 1,
      "explain": "Ownership and Earn Trust require being vocally self-critical. Disclosing scope and duration lets the ops team assess whether they made decisions on bad data — that is the customer impact."
    },
    {
      "scenario": "You have five things in your inbox: a customer-facing bug affecting orders, a teammate asking for a code review, your manager requesting a status update, a meeting starting in 10 minutes, and a request to update documentation.",
      "options": [
        "Handle them in the order they arrived",
        "Triage the customer bug first, send a one-line ack to the review and status requests with an ETA, join the meeting, and defer the docs",
        "Do the quick items first to clear the inbox, then the bug",
        "Ask your manager to prioritise for you"
      ],
      "best": 1,
      "explain": "Customer Obsession sets the order, but strong answers also acknowledge the others rather than dropping them silently. Clearing quick wins while customers are impacted is the wrong instinct."
    },
    {
      "scenario": "A metric dashboard says feature adoption is 40%. A teammate insists from user calls that 'almost nobody uses it'. Which is your next move?",
      "options": [
        "Trust the dashboard — data beats anecdote",
        "Trust the teammate — they talk to users",
        "Verify the metric definition and query yourself, and check whether 'adoption' counts something different from active use",
        "Escalate to the PM to decide"
      ],
      "best": 2,
      "explain": "Dive Deep explicitly says leaders are skeptical when metrics and anecdote differ. Usually the metric definition is the culprit — e.g. counting one-time visits as adoption."
    },
    {
      "scenario": "You are two days from a deadline and realise the proper fix needs a week. A hack would work but leaves a known edge case that could corrupt a small number of records.",
      "options": [
        "Ship the hack and file a follow-up ticket",
        "Ship the hack silently to hit the date",
        "Flag it now with the specific risk and record volume, propose either a scoped-down safe release or a short slip, and let the decision be made with full information",
        "Miss the deadline without telling anyone until the day"
      ],
      "best": 2,
      "explain": "Insist on the Highest Standards says defects must not get sent down the line. Data corruption is not an acceptable trade for a date, but the strong answer is transparent escalation with options, not a unilateral call."
    },
    {
      "scenario": "A new intern on your team is struggling with the codebase and is falling behind, but has not asked for help.",
      "options": [
        "Stay out of it — their mentor's job",
        "Offer a short pairing session, share the mental model of how the service fits together, and point them at the two docs that unblocked you",
        "Report the concern to their manager",
        "Do part of their task for them so the sprint is not affected"
      ],
      "best": 1,
      "explain": "Hire and Develop the Best plus Earn Trust. Help them build capability rather than reporting them or doing the work for them."
    },
    {
      "scenario": "Your manager asks for a solution to a vague requirement: 'make onboarding faster'. No metric, no scope.",
      "options": [
        "Start building the most obvious improvement immediately",
        "Wait for a fully specified ticket",
        "Identify the riskiest assumption, propose a measurable definition of 'faster' and a smallest-useful first slice, confirm it, then start",
        "Design a full re-architecture of onboarding"
      ],
      "best": 2,
      "explain": "Dive Deep plus Invent and Simplify plus Bias for Action. Clarify the highest-risk assumption and move with an explicit, reversible first step rather than either stalling or over-building."
    }
  ],
  "workstyle": [
    {
      "a": "I prefer to fully validate a plan before acting",
      "b": "I prefer to act on a reversible decision and adjust as I learn"
    },
    {
      "a": "I focus deeply on my assigned scope",
      "b": "I look for problems outside my scope and pick them up"
    },
    {
      "a": "I make decisions from data I gather myself",
      "b": "I rely on the judgement of experienced colleagues"
    },
    {
      "a": "I raise disagreements immediately, even when uncomfortable",
      "b": "I preserve team harmony and raise concerns privately later"
    },
    {
      "a": "I prefer detailed instructions before starting",
      "b": "I prefer an outcome and freedom on the method"
    },
    {
      "a": "I ship something imperfect and iterate",
      "b": "I hold a release until quality is high"
    },
    {
      "a": "I solve problems by digging into details myself",
      "b": "I solve problems by delegating and coordinating"
    },
    {
      "a": "I am energised by ambiguous problems",
      "b": "I am energised by well-defined problems"
    },
    {
      "a": "I openly share my own mistakes with the team",
      "b": "I resolve my mistakes quietly and move on"
    },
    {
      "a": "I optimise for long-term maintainability",
      "b": "I optimise for shipping the current commitment"
    },
    {
      "a": "I actively seek feedback that contradicts my view",
      "b": "I trust my judgement once I have decided"
    },
    {
      "a": "I do whatever task is needed, including unglamorous work",
      "b": "I focus on high-leverage technical work"
    }
  ]
};

/* ============================================================
   OA Trainer — app logic
   DATA is injected above this file by build.py (no fetch()).
   State is held in memory only; nothing is persisted between reloads.
   ============================================================ */
(function () {
  'use strict';

  var SECTIONS = DATA.meta.sections;
  var TOTAL_MIN = SECTIONS.reduce(function (a, s) {
    return a + s.minutes;
  }, 0);

  /* Optional dev override for timer testing: ?fast=SECONDS */
  var FAST = (function () {
    var m = /(?:\?|&)fast=(\d+)/.exec(location.search);
    return m ? parseInt(m[1], 10) : null;
  })();

  /* Leadership Principle mapping for the Workstyles section.
     side = the statement whose selection indicates the principle. */
  var WORKSTYLE_MAP = [
    { side: 'b', lp: 'Bias for Action', tag: 'act and adjust' },
    { side: 'b', lp: 'Ownership', tag: 'work outside your scope' },
    { side: 'a', lp: 'Dive Deep', tag: 'self-gathered data' },
    { side: 'a', lp: 'Have Backbone; Disagree and Commit', tag: 'raise disagreement early' },
    { side: 'b', lp: 'Ownership', tag: 'outcome over instructions' },
    { side: 'a', lp: 'Bias for Action', tag: 'ship and iterate' },
    { side: 'a', lp: 'Dive Deep', tag: 'dig into details yourself' },
    { side: 'a', lp: 'Invent and Simplify', tag: 'energised by ambiguity' },
    { side: 'a', lp: 'Earn Trust', tag: 'share your mistakes' },
    { side: 'a', lp: 'Insist on the Highest Standards', tag: 'long-term maintainability' },
    { side: 'a', lp: 'Are Right, A Lot', tag: 'seek contradicting feedback' },
    { side: 'a', lp: 'Ownership', tag: 'take unglamorous work' }
  ];

  var LP_ORDER = [
    'Ownership',
    'Bias for Action',
    'Dive Deep',
    'Earn Trust',
    'Have Backbone; Disagree and Commit',
    'Insist on the Highest Standards',
    'Invent and Simplify',
    'Are Right, A Lot'
  ];

  /* ---------- state ---------- */
  var state = null;
  function freshState() {
    return {
      screen: 'landing',
      queue: [],
      qidx: 0,
      mode: 'single',
      answers: {},
      code: {},
      used: {},
      results: {},
      cur: 0,
      reached: 0,
      hint: {},
      total: 0,
      remaining: 0,
      deadline: 0,
      timerId: null,
      pending: null
    };
  }
  state = freshState();

  /* ---------- dom refs ---------- */
  var main = document.getElementById('main');
  var timerEl = document.getElementById('timer');
  var timerValue = document.getElementById('timer-value');
  var timerMeta = document.getElementById('timer-meta');
  var timerFill = document.getElementById('timer-fill');
  var timerLabel = document.getElementById('timer-label');
  var chip = document.getElementById('section-chip');
  var live = document.getElementById('live');

  /* ---------- helpers ---------- */
  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }
  /* escape + render `inline code` spans */
  function md(s) {
    return esc(s).replace(/`([^`]+)`/g, '<code class="inline">$1</code>');
  }
  function sectionMeta(id) {
    for (var i = 0; i < SECTIONS.length; i++) if (SECTIONS[i].id === id) return SECTIONS[i];
    return null;
  }
  function items(id) {
    return DATA[id] || [];
  }
  function mmss(sec) {
    sec = Math.max(0, Math.round(sec));
    var m = Math.floor(sec / 60),
      s = sec % 60;
    return (m < 10 ? '0' : '') + m + ':' + (s < 10 ? '0' : '') + s;
  }
  function letter(i) {
    return ['A', 'B', 'C', 'D', 'E'][i] || String(i + 1);
  }
  function announce(msg) {
    live.textContent = msg;
  }
  function answersFor(id) {
    if (!state.answers[id]) {
      var arr = [];
      for (var i = 0; i < items(id).length; i++) arr.push(null);
      state.answers[id] = arr;
    }
    return state.answers[id];
  }
  function answeredCount(id) {
    return answersFor(id).filter(function (v) {
      return v !== null && v !== undefined;
    }).length;
  }
  function codeLines(src) {
    var rows = String(src).split('\n');
    var html = '';
    for (var i = 0; i < rows.length; i++) {
      html +=
        '<tr><td class="ln">' +
        (i + 1) +
        '</td><td class="src">' +
        (esc(rows[i]) || ' ') +
        '</td></tr>';
    }
    return (
      '<div class="code"><div class="code__bar"><span>buggy snippet</span><span>' +
      rows.length +
      ' lines</span></div><div class="code__scroll" tabindex="0" role="group" aria-label="Code snippet, scrollable"><table>' +
      html +
      '</table></div></div>'
    );
  }

  /* ---------- theme ---------- */
  (function theme() {
    var btn = document.querySelector('[data-theme-toggle]');
    var root = document.documentElement;
    /* Dark by default — this is exam software; light is opt-in via the toggle. */
    var mode = 'dark';
    function paint() {
      root.setAttribute('data-theme', mode);
      btn.setAttribute('aria-label', 'Switch to ' + (mode === 'dark' ? 'light' : 'dark') + ' mode');
      btn.innerHTML =
        mode === 'dark'
          ? '<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="5"/><path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42"/></svg>'
          : '<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>';
    }
    paint();
    btn.addEventListener('click', function () {
      mode = mode === 'dark' ? 'light' : 'dark';
      paint();
    });
  })();

  /* ---------- timer ---------- */
  function startTimer(seconds) {
    stopTimer();
    state.total = seconds;
    state.deadline = Date.now() + seconds * 1000;
    timerEl.hidden = false;
    tick();
    state.timerId = setInterval(tick, 250);
  }
  function stopTimer() {
    if (state.timerId) clearInterval(state.timerId);
    state.timerId = null;
  }
  function tick() {
    var remaining = Math.max(0, (state.deadline - Date.now()) / 1000);
    state.remaining = remaining;
    var elapsed = state.total - remaining;
    timerValue.textContent = mmss(remaining);
    timerMeta.textContent = 'elapsed ' + mmss(elapsed) + ' / ' + mmss(state.total);
    timerFill.style.width = (state.total ? (remaining / state.total) * 100 : 0) + '%';
    timerEl.classList.toggle('is-warn', remaining < 300 && remaining >= 60);
    timerEl.classList.toggle('is-crit', remaining < 60);
    timerLabel.textContent = remaining < 60 ? 'Submitting soon' : 'Time remaining';
    if (remaining <= 0) {
      stopTimer();
      submitSection(true);
    }
  }
  function hideTimer() {
    stopTimer();
    timerEl.hidden = true;
    timerEl.classList.remove('is-warn', 'is-crit');
  }

  /* ---------- flow ---------- */
  function currentSectionId() {
    return state.queue[state.qidx];
  }

  function startRun(queue, mode) {
    var keep = { hint: {} };
    state = freshState();
    state.hint = keep.hint;
    state.queue = queue.slice();
    state.mode = mode;
    state.qidx = 0;
    beginSection();
  }

  function beginSection() {
    var id = currentSectionId();
    var meta = sectionMeta(id);
    state.screen = 'exam';
    state.cur = 0;
    state.reached = 0;
    startTimer(FAST !== null ? FAST : meta.minutes * 60);
    render();
  }

  function submitSection(auto) {
    if (state.screen !== 'exam') return;
    var id = currentSectionId();
    var meta = sectionMeta(id);
    var list = items(id);
    var ans = answersFor(id);
    var correct = 0;
    if (id !== 'workstyle' && id !== 'coding') {
      for (var i = 0; i < list.length; i++) {
        var key = id === 'worksim' ? list[i].best : list[i].answer;
        if (ans[i] === key) correct++;
      }
    }
    state.used[id] = Math.min(state.total, state.total - state.remaining);
    state.results[id] = {
      id: id,
      name: meta.name,
      scored: id !== 'workstyle' && id !== 'coding',
      correct: correct,
      total: list.length,
      answered: answeredCount(id),
      timeUsed: state.used[id],
      limit: state.total,
      auto: !!auto
    };
    hideTimer();
    state.screen = 'result';
    state.pending = null;
    render();
    announce(
      (auto ? 'Time expired. Section auto-submitted. ' : 'Section submitted. ') +
        meta.name +
        ' results are shown.'
    );
    window.scrollTo(0, 0);
  }

  function nextSection() {
    state.qidx++;
    if (state.qidx >= state.queue.length) {
      state.screen = 'summary';
      render();
      window.scrollTo(0, 0);
    } else {
      beginSection();
      window.scrollTo(0, 0);
    }
  }

  function toLanding() {
    hideTimer();
    var s = freshState();
    s.answers = state.answers;
    s.code = state.code;
    s.results = state.results;
    s.used = state.used;
    state = s;
    state.screen = 'landing';
    render();
  }

  function hardReset() {
    hideTimer();
    state = freshState();
    render();
    announce('Progress reset.');
  }

  /* ---------- render: landing ---------- */
  function renderLanding() {
    chip.hidden = true;
    var rows = SECTIONS.map(function (s) {
      return (
        '<tr><td><span class="s-name">' +
        esc(s.name) +
        '</span><span class="s-note">' +
        esc(s.note) +
        '</span></td><td><span class="s-mins">' +
        s.minutes +
        ' min</span></td></tr>'
      );
    }).join('');

    var starts = SECTIONS.map(function (s) {
      var done = state.results[s.id];
      return (
        '<button class="start-row" type="button" data-start="' +
        s.id +
        '"><span><span class="start-row__name">' +
        esc(s.name) +
        '</span><br><span class="start-row__meta">' +
        items(s.id).length +
        ' items · ' +
        s.minutes +
        ' min' +
        (done ? ' · attempted' : '') +
        '</span></span><span class="start-row__meta">Start &rarr;</span></button>'
      );
    }).join('');

    main.innerHTML =
      '<section class="hero fade-in">' +
      '<p class="eyebrow">Timed mock assessment</p>' +
      '<h1>' +
      esc(DATA.meta.title) +
      '</h1>' +
      '<p>' +
      esc(DATA.meta.subtitle) +
      '. Six sections, strict per-section timers, no revisiting a section once it is submitted — exactly how the real assessment behaves. Sit it in one uninterrupted block if you can.</p>' +
      '<div class="hero__stats">' +
      '<div class="stat"><div class="stat__value">' +
      TOTAL_MIN +
      ' min</div><div class="stat__label">Full mock</div></div>' +
      '<div class="stat"><div class="stat__value">' +
      SECTIONS.length +
      '</div><div class="stat__label">Sections</div></div>' +
      '<div class="stat"><div class="stat__value">' +
      SECTIONS.reduce(function (a, s) {
        return a + items(s.id).length;
      }, 0) +
      '</div><div class="stat__label">Items</div></div>' +
      '</div></section>' +
      '<div class="section-grid">' +
      '<div class="panel"><h2 class="panel__title">Structure</h2>' +
      '<p class="panel__note">Sections run in this order in the full mock.</p>' +
      '<table class="sections-table"><thead><tr><th scope="col">Section</th><th scope="col">Duration</th></tr></thead><tbody>' +
      rows +
      '</tbody><tfoot><tr><td>Total</td><td>' +
      TOTAL_MIN +
      ' min</td></tr></tfoot></table></div>' +
      '<div>' +
      '<div class="panel"><h2 class="panel__title">Begin</h2>' +
      '<p class="panel__note">The timer starts the moment a section opens.</p>' +
      '<button class="btn btn--primary btn--block" type="button" id="start-full">Full mock (all sections in order)</button>' +
      '<span class="field-label">Or practise one section</span>' +
      '<div class="start-list">' +
      starts +
      '</div></div>' +
      '</div></div>' +
      '<div class="callout"><strong>Rules enforced here, as in the real OA</strong>' +
      '<ul>' +
      '<li>Timers are strict. At zero the section submits itself with whatever you have.</li>' +
      '<li>A submitted section cannot be reopened or revisited.</li>' +
      '<li>Logical Reasoning is one-way: once you advance, that question is closed.</li>' +
      '<li>Coding model solutions stay locked until you submit the section.</li>' +
      '<li>Workstyles is not scored — it is read for consistency across the whole set.</li>' +
      '</ul></div>';

    document.getElementById('start-full').addEventListener('click', function () {
      startRun(
        SECTIONS.map(function (s) {
          return s.id;
        }),
        'full'
      );
      window.scrollTo(0, 0);
    });
    Array.prototype.forEach.call(main.querySelectorAll('[data-start]'), function (b) {
      b.addEventListener('click', function () {
        startRun([b.getAttribute('data-start')], 'single');
        window.scrollTo(0, 0);
      });
    });
  }

  /* ---------- render: exam ---------- */
  var FREE_NAV = { debug: 1, corecs: 1, worksim: 1, workstyle: 1, coding: 1 };
  var PALETTE = { corecs: 1, debug: 1, worksim: 1, workstyle: 1 };

  function renderExam() {
    var id = currentSectionId();
    var meta = sectionMeta(id);
    var list = items(id);
    var n = list.length;
    var i = Math.min(state.cur, n - 1);
    state.cur = i;
    if (i > state.reached) state.reached = i;

    chip.hidden = false;
    chip.textContent =
      meta.name + ' · Q' + (i + 1) + '/' + n + (state.mode === 'full' ? ' · full mock' : '');

    var body = '';
    if (id === 'coding') body = codingBody(list[i], i, n);
    else if (id === 'workstyle') body = workstyleBody(list[i], i, n);
    else if (id === 'debug') body = debugBody(list[i], i, n);
    else body = mcqBody(list[i], i, n, id);

    var pct = (answeredCount(id) / n) * 100;
    var head =
      '<section class="exam-head">' +
      '<div><p class="eyebrow">' +
      (state.mode === 'full'
        ? 'Section ' + (state.qidx + 1) + ' of ' + state.queue.length
        : 'Single section') +
      '</p><h1>' +
      esc(meta.name) +
      '</h1></div>' +
      '<p class="exam-head__meta">' +
      esc(meta.note) +
      ' · ' +
      answeredCount(id) +
      '/' +
      n +
      ' recorded</p>' +
      '</section><div class="progress-bar"><div class="progress-bar__fill" style="width:' +
      pct +
      '%"></div></div>';

    var palette = PALETTE[id] ? paletteHtml(id, i, n) : '';
    main.innerHTML =
      head +
      '<div class="qwrap' +
      (palette ? ' qwrap--palette' : '') +
      '"><div class="qcard fade-in">' +
      body +
      navHtml(id, i, n) +
      '</div>' +
      palette +
      '</div>';

    wireExam(id, i, n);
  }

  function debugBody(q, i, n) {
    return (
      '<p class="qcard__num">Question ' +
      (i + 1) +
      ' / ' +
      n +
      '</p>' +
      '<h2 class="qcard__prompt">' +
      md(q.prompt) +
      '</h2>' +
      codeLines(q.code) +
      optionsHtml(q.options, i, 'debug')
    );
  }

  function mcqBody(q, i, n, id) {
    var topic = q.topic
      ? '<div class="badge-row"><span class="badge badge--accent">' + esc(q.topic) + '</span></div>'
      : '';
    var text = id === 'worksim' ? q.scenario : q.q;
    var oneWay =
      id === 'reasoning'
        ? '<div class="badge-row"><span class="badge">one-way · no going back</span></div>'
        : '';
    return (
      '<p class="qcard__num">Question ' +
      (i + 1) +
      ' / ' +
      n +
      '</p>' +
      topic +
      oneWay +
      (id === 'worksim'
        ? '<h2 class="qcard__prompt">Scenario</h2><p class="qcard__scenario">' +
          md(text) +
          '</p><p class="field-label" style="margin-top:0">What do you do?</p>'
        : '<h2 class="qcard__prompt">' + md(text) + '</h2>') +
      optionsHtml(q.options, i, id)
    );
  }

  function optionsHtml(options, qi, id) {
    var sel = answersFor(id)[qi];
    var opts = options
      .map(function (o, k) {
        return (
          '<button class="opt' +
          (sel === k ? ' is-selected' : '') +
          '" type="button" role="radio" aria-checked="' +
          (sel === k ? 'true' : 'false') +
          '" data-opt="' +
          k +
          '"><span class="opt__key" aria-hidden="true">' +
          (k + 1) +
          '</span><span class="opt__text">' +
          md(o) +
          '</span></button>'
        );
      })
      .join('');
    return (
      '<div class="options" role="radiogroup" aria-label="Answer options for question ' +
      (qi + 1) +
      '">' +
      opts +
      '</div>'
    );
  }

  function workstyleBody(q, i, n) {
    var sel = answersFor('workstyle')[i];
    function card(side, txt) {
      return (
        '<button class="pair__card' +
        (sel === side ? ' is-selected' : '') +
        '" type="button" role="radio" aria-checked="' +
        (sel === side ? 'true' : 'false') +
        '" data-side="' +
        side +
        '"><span class="pair__tag">' +
        (side === 'a' ? '1 · Statement A' : '2 · Statement B') +
        '</span><span class="pair__stmt">' +
        md(txt) +
        '</span><span class="badge">' +
        (sel === side ? 'selected' : 'choose this') +
        '</span></button>'
      );
    }
    return (
      '<p class="qcard__num">Pair ' +
      (i + 1) +
      ' / ' +
      n +
      '</p>' +
      '<h2 class="qcard__prompt">Which statement describes you better?</h2>' +
      '<p class="qcard__scenario">There is no correct answer. Answer as you actually work — Amazon reads the whole set for consistency.</p>' +
      '<div class="pair">' +
      card('a', q.a) +
      card('b', q.b) +
      '</div>'
    );
  }

  function codingBody(q, i, n) {
    var val = state.code[q.id] || '';
    var open = !!state.hint[q.id];
    return (
      '<p class="qcard__num">Problem ' +
      (i + 1) +
      ' / ' +
      n +
      '</p>' +
      '<h2 class="qcard__prompt">' +
      esc(q.title) +
      '</h2>' +
      '<div class="badge-row"><span class="badge badge--accent">' +
      esc(q.difficulty) +
      '</span><span class="badge">suggested ' +
      q.suggested +
      ' min</span><span class="badge">' +
      esc(q.source) +
      '</span></div>' +
      '<div class="statement">' +
      esc(q.statement) +
      '</div>' +
      '<label class="field-label" for="editor">Your approach and code</label>' +
      '<textarea class="editor" id="editor" spellcheck="false" placeholder="1. Restate the problem.\n2. Approach and why it is correct.\n3. Complexity.\n4. Code.">' +
      esc(val) +
      '</textarea>' +
      '<div class="tool-row">' +
      '<button class="btn btn--outline btn--sm" type="button" id="hint-btn" aria-expanded="' +
      (open ? 'true' : 'false') +
      '" aria-controls="hint-box">' +
      (open ? 'Hide hint' : 'Show hint') +
      '</button>' +
      '<button class="btn btn--outline btn--sm" type="button" disabled title="Unlocks after you submit this section">Reveal model solution (locked)</button>' +
      '<span class="saved-note" id="saved-note">autosaved · ' +
      val.length +
      ' chars</span>' +
      '</div>' +
      (open ? '<div class="hint-box" id="hint-box"><strong>Hint.</strong> ' + md(q.hint) + '</div>' : '')
    );
  }

  function paletteHtml(id, cur, n) {
    var ans = answersFor(id);
    var btns = '';
    for (var k = 0; k < n; k++) {
      var done = ans[k] !== null && ans[k] !== undefined;
      btns +=
        '<button class="pbtn' +
        (done ? ' is-answered' : '') +
        (k === cur ? ' is-current' : '') +
        '" type="button" data-goto="' +
        k +
        '" aria-label="Question ' +
        (k + 1) +
        (done ? ', answered' : ', unanswered') +
        '"' +
        (k === cur ? ' aria-current="true"' : '') +
        '>' +
        (k + 1) +
        '</button>';
    }
    return (
      '<aside class="palette" aria-label="Question palette"><p class="palette__title">Questions</p>' +
      '<div class="palette__grid">' +
      btns +
      '</div><div class="palette__legend">' +
      '<span class="legend-row"><span class="legend-dot legend-dot--ans"></span>answered</span>' +
      '<span class="legend-row"><span class="legend-dot"></span>not answered</span>' +
      '<span class="legend-row"><span class="legend-dot legend-dot--cur"></span>current</span>' +
      '</div></aside>'
    );
  }

  function navHtml(id, i, n) {
    var free = !!FREE_NAV[id];
    var prev =
      free && i > 0
        ? '<button class="btn btn--outline" type="button" id="prev-btn">&larr; Previous</button>'
        : '';
    var next =
      i < n - 1
        ? '<button class="btn btn--primary" type="button" id="next-btn">Next &rarr;</button>'
        : '';
    var submit =
      '<button class="btn ' +
      (i === n - 1 ? 'btn--primary' : 'btn--danger') +
      '" type="button" id="submit-btn">Submit section</button>';
    return (
      '<div class="navbar">' +
      prev +
      next +
      '<span class="navbar__spacer"></span>' +
      submit +
      '<p class="navbar__hint">Keys: ' +
      (id === 'workstyle'
        ? '1 / 2 pick a statement'
        : id === 'coding'
          ? 'type freely in the editor'
          : '1–4 select an option') +
      (id === 'coding' ? ' · &rarr; next problem' : ' · Enter or &rarr; next') +
      (free && i > 0 ? ' · &larr; previous' : '') +
      (id === 'reasoning' ? ' · answers close when you advance' : '') +
      '</p></div>'
    );
  }

  function wireExam(id, i, n) {
    Array.prototype.forEach.call(main.querySelectorAll('[data-opt]'), function (b) {
      b.addEventListener('click', function () {
        select(id, i, parseInt(b.getAttribute('data-opt'), 10));
      });
    });
    Array.prototype.forEach.call(main.querySelectorAll('[data-side]'), function (b) {
      b.addEventListener('click', function () {
        select(id, i, b.getAttribute('data-side'));
      });
    });
    Array.prototype.forEach.call(main.querySelectorAll('[data-goto]'), function (b) {
      b.addEventListener('click', function () {
        state.cur = parseInt(b.getAttribute('data-goto'), 10);
        render();
      });
    });
    var prev = document.getElementById('prev-btn');
    if (prev) prev.addEventListener('click', goPrev);
    var next = document.getElementById('next-btn');
    if (next) next.addEventListener('click', goNext);
    document.getElementById('submit-btn').addEventListener('click', function () {
      confirmSubmit(id);
    });

    var ed = document.getElementById('editor');
    if (ed) {
      var q = items('coding')[i];
      ed.addEventListener('input', function () {
        state.code[q.id] = ed.value;
        var note = document.getElementById('saved-note');
        if (note) note.textContent = 'autosaved · ' + ed.value.length + ' chars';
      });
      var hb = document.getElementById('hint-btn');
      hb.addEventListener('click', function () {
        state.hint[q.id] = !state.hint[q.id];
        render();
      });
    }
  }

  function select(id, i, value) {
    answersFor(id)[i] = value;
    render();
  }
  function goNext() {
    var id = currentSectionId();
    if (state.cur < items(id).length - 1) {
      state.cur++;
      render();
      window.scrollTo(0, 0);
    }
  }
  function goPrev() {
    var id = currentSectionId();
    if (FREE_NAV[id] && state.cur > 0) {
      state.cur--;
      render();
      window.scrollTo(0, 0);
    }
  }

  function confirmSubmit(id) {
    var n = items(id).length;
    var left = n - answeredCount(id);
    openModal(
      'Submit ' + sectionMeta(id).name + '?',
      (left > 0
        ? left + ' of ' + n + ' items are unanswered. '
        : 'All ' + n + ' items are recorded. ') +
        'You cannot reopen this section afterwards.',
      'Submit section',
      function () {
        submitSection(false);
      }
    );
  }

  function openModal(title, text, confirmLabel, onConfirm) {
    var wrap = document.createElement('div');
    wrap.className = 'modal-backdrop';
    wrap.innerHTML =
      '<div class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><h2 id="modal-title">' +
      esc(title) +
      '</h2><p>' +
      esc(text) +
      '</p><div class="action-row"><button class="btn btn--primary" type="button" id="modal-ok">' +
      esc(confirmLabel) +
      '</button><button class="btn btn--ghost" type="button" id="modal-cancel">Cancel</button></div></div>';
    document.body.appendChild(wrap);
    var ok = wrap.querySelector('#modal-ok');
    ok.focus();
    function close() {
      wrap.remove();
    }
    ok.addEventListener('click', function () {
      close();
      onConfirm();
    });
    wrap.querySelector('#modal-cancel').addEventListener('click', close);
    wrap.addEventListener('click', function (e) {
      if (e.target === wrap) close();
    });
    wrap.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') close();
    });
  }

  /* ---------- render: section results ---------- */
  function renderResult() {
    var id = currentSectionId();
    var r = state.results[id];
    chip.hidden = false;
    chip.textContent = r.name + ' · submitted';

    var head =
      '<section class="exam-head"><div><p class="eyebrow">' +
      (r.auto ? 'Time expired — auto-submitted' : 'Section submitted') +
      '</p><h1>' +
      esc(r.name) +
      ' — results</h1></div><p class="exam-head__meta">' +
      mmss(r.timeUsed) +
      ' used of ' +
      mmss(r.limit) +
      '</p></section>';

    var strip;
    if (r.scored) {
      var pct = r.total ? Math.round((r.correct / r.total) * 100) : 0;
      strip =
        '<div class="score-strip">' +
        cell('Score', r.correct + ' / ' + r.total, true) +
        cell('Percentage', pct + '%') +
        cell('Answered', r.answered + ' / ' + r.total) +
        cell('Time used', mmss(r.timeUsed)) +
        '</div>';
    } else if (id === 'coding') {
      strip =
        '<div class="score-strip">' +
        cell('Problems attempted', r.attemptedCoding !== undefined ? r.attemptedCoding : codingAttempted() + ' / ' + r.total, true) +
        cell('Scoring', 'self-assess') +
        cell('Time used', mmss(r.timeUsed)) +
        '</div>';
    } else {
      strip =
        '<div class="score-strip">' +
        cell('Pairs answered', r.answered + ' / ' + r.total, true) +
        cell('Scoring', 'not scored') +
        cell('Time used', mmss(r.timeUsed)) +
        '</div>';
    }

    var body;
    if (id === 'coding') body = codingReview();
    else if (id === 'workstyle') body = workstyleReadout();
    else body = mcqReview(id);

    var actions =
      '<div class="action-row">' +
      (state.mode === 'full'
        ? '<button class="btn btn--primary" type="button" id="cont-btn">' +
          (state.qidx < state.queue.length - 1
            ? 'Start next section: ' + esc(sectionMeta(state.queue[state.qidx + 1]).name)
            : 'View full mock summary') +
          '</button>'
        : '') +
      '<button class="btn btn--outline" type="button" id="home-btn">Back to sections</button>' +
      '</div>';

    main.innerHTML = head + strip + body + actions;
    var c = document.getElementById('cont-btn');
    if (c)
      c.addEventListener('click', function () {
        nextSection();
      });
    document.getElementById('home-btn').addEventListener('click', toLanding);
  }

  function cell(label, value, accent) {
    return (
      '<div class="score-cell' +
      (accent ? ' score-cell--accent' : '') +
      '"><p class="score-cell__label">' +
      esc(label) +
      '</p><p class="score-cell__value">' +
      esc(value) +
      '</p></div>'
    );
  }

  function codingAttempted() {
    return items('coding').filter(function (q) {
      return (state.code[q.id] || '').trim().length > 0;
    }).length;
  }

  function mcqReview(id) {
    var list = items(id);
    var ans = answersFor(id);
    var html =
      '<h2 class="panel__title">Review</h2><p class="panel__note">Every item, your answer, the correct answer and why.</p><div class="review">';
    for (var i = 0; i < list.length; i++) {
      var q = list[i];
      var key = id === 'worksim' ? q.best : q.answer;
      var mine = ans[i];
      var ok = mine === key;
      var text = id === 'worksim' ? q.scenario : q.q;
      html +=
        '<article class="review__item ' +
        (ok ? 'is-correct' : 'is-wrong') +
        '"><div class="review__head"><span class="badge">Q' +
        (i + 1) +
        (q.topic ? ' · ' + esc(q.topic) : '') +
        '</span><span class="badge ' +
        (ok ? 'badge--ok">correct' : 'badge--bad">' + (mine === null || mine === undefined ? 'not answered' : 'incorrect')) +
        '</span></div>' +
        '<p class="review__q">' +
        md(text) +
        '</p>' +
        (id === 'debug' ? codeLines(q.code) : '') +
        '<div class="review__row"><span class="review__key">Your answer</span><span class="review__val ' +
        (ok ? 'ok' : 'bad') +
        '">' +
        (mine === null || mine === undefined
          ? '— none —'
          : letter(mine) + '. ' + md(q.options[mine])) +
        '</span></div>' +
        '<div class="review__row"><span class="review__key">' +
        (id === 'worksim' ? 'Best answer' : 'Correct') +
        '</span><span class="review__val ok">' +
        letter(key) +
        '. ' +
        md(q.options[key]) +
        '</span></div>' +
        '<p class="explain">' +
        md(q.explain) +
        '</p></article>';
    }
    return html + '</div>';
  }

  function codingReview() {
    var list = items('coding');
    var html =
      '<h2 class="panel__title">Self-assessment</h2><p class="panel__note">Amazon graders read correctness, complexity and clarity. Compare your write-up against the model approach line by line and mark yourself honestly.</p><div class="review">';
    for (var i = 0; i < list.length; i++) {
      var q = list[i];
      var mine = (state.code[q.id] || '').trim();
      html +=
        '<article class="review__item"><div class="review__head"><span class="badge badge--accent">' +
        esc(q.title) +
        '</span><span class="badge">' +
        esc(q.difficulty) +
        ' · self-assess</span></div>' +
        '<div class="split">' +
        '<div><span class="field-label" style="margin-top:0">Your submission</span><pre class="plain">' +
        (mine ? esc(mine) : 'Nothing submitted for this problem.') +
        '</pre></div>' +
        '<div><span class="field-label" style="margin-top:0">Model approach</span><p style="font-size:var(--text-sm)">' +
        md(q.approach) +
        '</p><span class="field-label">Complexity</span><p style="font-size:var(--text-sm)"><code class="inline">' +
        esc(q.complexity) +
        '</code></p></div>' +
        '</div>' +
        '<span class="field-label">Model solution</span><pre class="plain">' +
        esc(q.solution) +
        '</pre>' +
        '<p class="explain"><strong>Hint you had available:</strong> ' +
        md(q.hint) +
        '</p></article>';
    }
    return html + '</div>';
  }

  function workstyleReadout() {
    var list = items('workstyle');
    var ans = answersFor('workstyle');
    var counts = {},
      totals = {};
    for (var i = 0; i < list.length; i++) {
      var m = WORKSTYLE_MAP[i];
      totals[m.lp] = (totals[m.lp] || 0) + 1;
      if (ans[i] === m.side) counts[m.lp] = (counts[m.lp] || 0) + 1;
      else counts[m.lp] = counts[m.lp] || 0;
    }
    var rows = LP_ORDER.filter(function (lp) {
      return totals[lp];
    })
      .map(function (lp) {
        var c = counts[lp],
          t = totals[lp];
        return (
          '<div class="lp-row"><span class="lp-name">' +
          esc(lp) +
          '</span><span class="lp-track"><span class="lp-fill" style="width:' +
          (t ? (c / t) * 100 : 0) +
          '%"></span></span><span class="lp-count">' +
          c +
          '/' +
          t +
          ' leaning</span></div>'
        );
      })
      .join('');

    var detail = list
      .map(function (q, i) {
        var m = WORKSTYLE_MAP[i];
        var picked = ans[i];
        var aligned = picked === m.side;
        return (
          '<article class="review__item"><div class="review__head"><span class="badge">Pair ' +
          (i + 1) +
          '</span><span class="badge ' +
          (picked === null || picked === undefined
            ? '">not answered'
            : aligned
              ? 'badge--accent">' + esc(m.lp)
              : '">other side') +
          '</span></div>' +
          '<div class="review__row"><span class="review__key">Statement A</span><span class="review__val' +
          (picked === 'a' ? ' ok' : '') +
          '">' +
          md(q.a) +
          '</span></div>' +
          '<div class="review__row"><span class="review__key">Statement B</span><span class="review__val' +
          (picked === 'b' ? ' ok' : '') +
          '">' +
          md(q.b) +
          '</span></div>' +
          '<p class="explain">Choosing the <strong>' +
          esc(m.tag) +
          '</strong> statement indicates <strong>' +
          esc(m.lp) +
          '</strong>. Neither side is wrong; what matters is whether your answers across all twelve pairs tell one coherent story.</p></article>'
        );
      })
      .join('');

    return (
      '<div class="panel"><h2 class="panel__title">Leadership Principle leanings</h2>' +
      '<p class="panel__note">Derived from which side of each pair you picked. This is a directional read-out, not a score.</p>' +
      '<div class="lp-list">' +
      rows +
      '</div></div>' +
      '<div class="callout"><strong>What Amazon actually measures.</strong> Workstyles is not marked right or wrong. It is checked for internal consistency: the same trait is probed from several angles, and contradictory answers stand out far more than any single "wrong" choice. Do not try to guess the answer Amazon wants — answer as the engineer you actually are, and be ready to defend every leaning with a real story in the interview.</div>' +
      '<h2 class="panel__title" style="margin-top:var(--space-10)">Your choices</h2><div class="review">' +
      detail +
      '</div>'
    );
  }

  /* ---------- render: final summary ---------- */
  function renderSummary() {
    hideTimer();
    chip.hidden = false;
    chip.textContent = 'Full mock complete';

    var scoredCorrect = 0,
      scoredTotal = 0,
      timeTotal = 0;
    var rows = state.queue
      .map(function (id) {
        var r = state.results[id];
        if (!r) return '';
        timeTotal += r.timeUsed;
        var scoreTxt;
        if (r.scored) {
          scoredCorrect += r.correct;
          scoredTotal += r.total;
          scoreTxt = r.correct + ' / ' + r.total;
        } else if (id === 'coding') {
          scoreTxt = codingAttempted() + ' / ' + r.total + ' attempted';
        } else {
          scoreTxt = r.answered + ' / ' + r.total + ' answered';
        }
        var pct = r.scored ? Math.round((r.correct / r.total) * 100) + '%' : '—';
        return (
          '<tr><td>' +
          esc(r.name) +
          (r.auto ? ' <span class="badge badge--bad">auto-submitted</span>' : '') +
          '</td><td>' +
          scoreTxt +
          '</td><td>' +
          pct +
          '</td><td>' +
          mmss(r.timeUsed) +
          '</td></tr>'
        );
      })
      .join('');

    var pctAll = scoredTotal ? Math.round((scoredCorrect / scoredTotal) * 100) : 0;

    main.innerHTML =
      '<section class="hero fade-in"><p class="eyebrow">Full mock complete</p><h1>Your calibration report</h1>' +
      '<p>MCQ sections are objective and scored below. Coding and Workstyles are deliberately not scored here — read the guidance before you draw conclusions.</p></section>' +
      '<div class="score-strip">' +
      cell('MCQ total', scoredCorrect + ' / ' + scoredTotal, true) +
      cell('MCQ percentage', pctAll + '%') +
      cell('Coding attempted', codingAttempted() + ' / ' + items('coding').length) +
      cell('Total time used', mmss(timeTotal)) +
      '</div>' +
      '<div class="panel"><h2 class="panel__title">Per section</h2><table class="summary-table"><thead><tr><th scope="col">Section</th><th scope="col">Result</th><th scope="col">%</th><th scope="col">Time</th></tr></thead><tbody>' +
      rows +
      '</tbody><tfoot><tr><td>Scored MCQ subtotal</td><td>' +
      scoredCorrect +
      ' / ' +
      scoredTotal +
      '</td><td>' +
      pctAll +
      '%</td><td>' +
      mmss(timeTotal) +
      '</td></tr></tfoot></table></div>' +
      '<div class="callout"><strong>Honest calibration.</strong>' +
      '<ul>' +
      '<li><strong>The two coding problems decide the outcome.</strong> Amazon weights the coding assessment far above everything else. A clean, fully working solution with correct complexity on both problems is what moves you forward.</li>' +
      '<li><strong>A strong MCQ score does not compensate for weak coding.</strong> Core CS, reasoning and debugging screen out; they do not pull you up. ' +
      pctAll +
      '% on MCQs with one broken coding solution is a weaker profile than an average MCQ score with two solid ones.</li>' +
      '<li><strong>Judge your coding answers against the model approach, not against your memory of feeling confident.</strong> If you did not state a complexity, you did not finish the answer.</li>' +
      '<li><strong>Workstyles is unscored on purpose.</strong> Consistency across the full set is the signal — gaming individual pairs is visible.</li>' +
      '<li><strong>Time is part of the test.</strong> ' +
      mmss(timeTotal) +
      ' of ' +
      TOTAL_MIN +
      ' minutes used. Sections you auto-submitted are flagged above; those are pacing failures to fix before the real sitting.</li>' +
      '</ul></div>' +
      '<div class="action-row"><button class="btn btn--primary" type="button" id="again-btn">Reset and sit it again</button>' +
      '<button class="btn btn--outline" type="button" id="home-btn">Back to sections</button></div>';

    document.getElementById('again-btn').addEventListener('click', hardReset);
    document.getElementById('home-btn').addEventListener('click', toLanding);
  }

  /* ---------- router ---------- */
  function render() {
    if (state.screen === 'landing') renderLanding();
    else if (state.screen === 'exam') renderExam();
    else if (state.screen === 'result') renderResult();
    else renderSummary();
  }

  /* ---------- global controls ---------- */
  document.getElementById('reset-btn').addEventListener('click', function () {
    openModal(
      'Reset everything?',
      'All answers, code and results are held in memory only and will be cleared immediately.',
      'Reset',
      hardReset
    );
  });

  document.addEventListener('keydown', function (e) {
    if (document.querySelector('.modal-backdrop')) return;
    var tag = (e.target.tagName || '').toLowerCase();
    if (tag === 'textarea' || tag === 'input') return;
    if (state.screen !== 'exam') return;
    var id = currentSectionId();
    var n = items(id).length;
    var i = state.cur;

    if (e.key >= '1' && e.key <= '9') {
      var k = parseInt(e.key, 10) - 1;
      if (id === 'workstyle') {
        if (k < 2) {
          e.preventDefault();
          select(id, i, k === 0 ? 'a' : 'b');
        }
        return;
      }
      if (id === 'coding') return;
      var q = items(id)[i];
      if (k < q.options.length) {
        e.preventDefault();
        select(id, i, k);
      }
      return;
    }
    if (e.key === 'Enter' || e.key === 'ArrowRight') {
      if (id === 'coding' && e.key === 'Enter') return;
      e.preventDefault();
      if (i < n - 1) goNext();
      else confirmSubmit(id);
    } else if (e.key === 'ArrowLeft') {
      e.preventDefault();
      goPrev();
    }
  });

  render();
})();
