#!/usr/bin/env python3
"""Inline questions.json into app.js (no fetch: local JSON fetch fails in sandboxed iframes)."""
import json, pathlib
d = pathlib.Path(__file__).parent
data = json.loads((d / "questions.json").read_text())
core = (d / "app.core.js").read_text()
header = ("/* AUTO-GENERATED by build.py — edit questions.json + app.core.js, then re-run. */\n"
          "var DATA = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n\n")
(d / "app.js").write_text(header + core)
print("app.js written:", len(header + core), "bytes")
